### ISSUE TITLE
SyntaxError: Generator expression must be parenthesized

### ISSUE THREAD

**Issue by LTGDev** [rdegges/brute#14]
I'm trying to run the following:

`from hashlib import sha256
from brute import brute

def brute_force():
                     
    expected = str.lower("49192A4F3F3")

    for pwd in brute(length=7, letters=False, numbers=True, symbols=False):
        hashed = sha256(pwd.encode('utf-8')).hexdigest()

        if hashed.startswith(expected):
            print(pwd)
`

However, I get the error:

Traceback (most recent call last):
  File "/home/kali/Desktop/script.py", line 2, in <module>
    from brute import brute
  File "/home/kali/.local/lib/python3.10/site-packages/brute.py", line 68
    product(
    ^^^^^^^^
SyntaxError: Generator expression must be parenthesized

**Comment by rdegges** [comment]
Working on this -- this package is quite old, I'm modernizing it now which means it should fix this shortly. Stay tuned!
